[package]
name = "STS1_EDU_Scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
simplelog = "0.11.0"
subprocess = "0.2.8"
crc = "3.0.0"
rppal = "0.13.1"