[workspace]
resolver = "2"
members = [
    "scheduler",
    "filevec",
    "simple-archive"
]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
module_name_repetitions = "allow"
missing_panics_doc = "allow"
