name: Software Tests

on:
  push:
    branches: [ "rust_dev" ]
  pull_request:
    branches: [ "rust_dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: sudo apt install socat
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --features mock
