name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: sudo apt install socat libudev-dev
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --features mock

  cross-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Build
      run: |
        cross build --examples --bins --release --target aarch64-unknown-linux-gnu
        mv target/aarch64-unknown-linux-gnu/release/STS1_EDU_Scheduler .
        mv target/aarch64-unknown-linux-gnu/release/examples/cli .
        cp scheduler/config.toml .
        cp scheduler/scheduler.service .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aarch64 package
        path: |
          STS1_EDU_Scheduler
          config.toml
          scheduler.service
          cli
