name: Build & Test

on:
  push:
    branches: [ "rust_dev" ]
  pull_request:
    branches: [ "rust_dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: sudo apt install socat
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --features mock

  cross-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Build
      run: cross build --release --target aarch64-unknown-linux-gnu
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aarch64 binary
        path: target/aarch64-unknown-linux-gnu/release/STS1_EDU_Scheduler
