name: Build & Test

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: sudo apt install socat libudev-dev
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --features mock

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: sudo apt install libudev-dev
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Formatting
        run: cargo fmt --all --check
